#include "ds4.h"

#include <errno.h>
#include <float.h>
#include <limits.h>
#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#ifndef DS4_DEFAULT_CYBERNEUROVA_MODEL
#define DS4_DEFAULT_CYBERNEUROVA_MODEL "/home/nick/.cache/huggingface/hub/models--cyberneurova--CyberNeurova-DeepSeek-V4-Flash-abliterated-GGUF/snapshots/665c8e035e2602d12d28b84920808b158f337e09/cyberneurova-DeepSeek-V4-Flash-abliterated-Q2_K.gguf"
#endif

typedef struct {
    const char *model_path;
    const char *prompt_path;
    const char *chat_prompt_path;
    const char *system;
    const char *draft_list;
    ds4_backend backend;
    int threads;
    int ctx;
    int prompt_tokens;
    int gen_tokens;
    bool quality;
    bool warm_weights;
} cfg_t;

typedef struct {
    FILE *fp;
    uint64_t len;
} snapshot_t;

static double now_sec(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (double)ts.tv_sec + (double)ts.tv_nsec / 1000000000.0;
}

static void usage(FILE *fp) {
    fprintf(fp,
        "Usage: ds4-mtp-oracle-microbench-rocm-upstream --prompt-file FILE [options]\n"
        "\n"
        "Measures the upper bound for a same-model speculative/MTP drafter by\n"
        "using oracle draft tokens generated by the target model.  Each cycle\n"
        "commits one normal exact decode token, then commits N oracle draft\n"
        "tokens via ds4_session_sync() resumed prefill.  This does not prove a\n"
        "drafter exists; it answers whether verification/commit batching is worth\n"
        "building.\n"
        "\n"
        "Options:\n"
        "  -m, --model FILE          GGUF model. Default: CyberNeurova Q2_K path\n"
        "  --prompt-file FILE        Raw prompt text\n"
        "  --chat-prompt-file FILE   Render FILE as one no-thinking chat prompt\n"
        "  -sys, --system TEXT       System prompt for --chat-prompt-file\n"
        "  --prompt-tokens N         Truncate tokenized prompt to first N tokens\n"
        "  --gen-tokens N            Target continuation length. Default: 64\n"
        "  --drafts LIST             Comma list of oracle draft depths. Default: 1,2,4,8\n"
        "  --ctx N                   Allocated context. Default: prompt+gen+16\n"
        "  --quality                 Prefer exact kernels where applicable\n"
        "  --warm-weights            Touch mapped tensor pages before benchmarking\n"
        "  --backend NAME            gpu/cuda/hip/metal/cpu. Default: gpu\n"
        "  -h, --help                Show this help\n");
}

static int parse_int(const char *s, const char *opt) {
    char *end = NULL;
    long v = strtol(s, &end, 10);
    if (!s || s[0] == '\0' || *end != '\0' || v <= 0 || v > INT_MAX) {
        fprintf(stderr, "mtp-oracle: invalid value for %s: %s\n", opt, s ? s : "(null)");
        exit(2);
    }
    return (int)v;
}

static const char *need_arg(int *i, int argc, char **argv, const char *opt) {
    if (*i + 1 >= argc) {
        fprintf(stderr, "mtp-oracle: %s requires an argument\n", opt);
        exit(2);
    }
    return argv[++*i];
}

static ds4_backend parse_backend(const char *s, const char *opt) {
    if (!strcmp(s, "gpu") || !strcmp(s, "cuda") || !strcmp(s, "hip") || !strcmp(s, "metal")) {
        return DS4_BACKEND_GPU;
    }
    if (!strcmp(s, "cpu")) return DS4_BACKEND_CPU;
    fprintf(stderr, "mtp-oracle: invalid value for %s: %s\n", opt, s);
    exit(2);
}

static char *read_file(const char *path) {
    FILE *fp = fopen(path, "rb");
    if (!fp) {
        fprintf(stderr, "mtp-oracle: failed to open %s: %s\n", path, strerror(errno));
        exit(1);
    }
    if (fseek(fp, 0, SEEK_END) != 0) {
        fprintf(stderr, "mtp-oracle: failed to seek %s\n", path);
        fclose(fp);
        exit(1);
    }
    long n = ftell(fp);
    if (n < 0) {
        fprintf(stderr, "mtp-oracle: failed to tell %s\n", path);
        fclose(fp);
        exit(1);
    }
    if (fseek(fp, 0, SEEK_SET) != 0) {
        fprintf(stderr, "mtp-oracle: failed to rewind %s\n", path);
        fclose(fp);
        exit(1);
    }
    char *buf = malloc((size_t)n + 1);
    if (!buf) {
        fprintf(stderr, "mtp-oracle: out of memory reading %s\n", path);
        fclose(fp);
        exit(1);
    }
    if (fread(buf, 1, (size_t)n, fp) != (size_t)n) {
        fprintf(stderr, "mtp-oracle: failed to read %s\n", path);
        free(buf);
        fclose(fp);
        exit(1);
    }
    fclose(fp);
    buf[n] = '\0';
    return buf;
}

static cfg_t parse_args(int argc, char **argv) {
    cfg_t c = {
        .model_path = DS4_DEFAULT_CYBERNEUROVA_MODEL,
        .system = "You are a helpful assistant.",
        .draft_list = "1,2,4,8",
        .backend = DS4_BACKEND_GPU,
        .gen_tokens = 64,
    };
    for (int i = 1; i < argc; i++) {
        const char *arg = argv[i];
        if (!strcmp(arg, "-h") || !strcmp(arg, "--help")) {
            usage(stdout);
            exit(0);
        } else if (!strcmp(arg, "-m") || !strcmp(arg, "--model")) {
            c.model_path = need_arg(&i, argc, argv, arg);
        } else if (!strcmp(arg, "--prompt-file")) {
            c.prompt_path = need_arg(&i, argc, argv, arg);
        } else if (!strcmp(arg, "--chat-prompt-file")) {
            c.chat_prompt_path = need_arg(&i, argc, argv, arg);
        } else if (!strcmp(arg, "-sys") || !strcmp(arg, "--system")) {
            c.system = need_arg(&i, argc, argv, arg);
        } else if (!strcmp(arg, "--prompt-tokens")) {
            c.prompt_tokens = parse_int(need_arg(&i, argc, argv, arg), arg);
        } else if (!strcmp(arg, "--gen-tokens") || !strcmp(arg, "--tokens") || !strcmp(arg, "-n")) {
            c.gen_tokens = parse_int(need_arg(&i, argc, argv, arg), arg);
        } else if (!strcmp(arg, "--drafts")) {
            c.draft_list = need_arg(&i, argc, argv, arg);
        } else if (!strcmp(arg, "--ctx")) {
            c.ctx = parse_int(need_arg(&i, argc, argv, arg), arg);
        } else if (!strcmp(arg, "--backend")) {
            c.backend = parse_backend(need_arg(&i, argc, argv, arg), arg);
        } else if (!strcmp(arg, "--quality")) {
            c.quality = true;
        } else if (!strcmp(arg, "--warm-weights")) {
            c.warm_weights = true;
        } else if (!strcmp(arg, "-t") || !strcmp(arg, "--threads")) {
            c.threads = parse_int(need_arg(&i, argc, argv, arg), arg);
        } else {
            fprintf(stderr, "mtp-oracle: unknown option: %s\n", arg);
            usage(stderr);
            exit(2);
        }
    }
    if (!!c.prompt_path == !!c.chat_prompt_path) {
        fprintf(stderr, "mtp-oracle: specify exactly one of --prompt-file or --chat-prompt-file\n");
        exit(2);
    }
    return c;
}

static int parse_drafts(const char *s, int *out, int cap) {
    int n = 0;
    const char *p = s;
    while (*p) {
        while (*p == ',' || *p == ' ' || *p == '\t') p++;
        if (!*p) break;
        char *end = NULL;
        long v = strtol(p, &end, 10);
        if (end == p || v < 0 || v > 64 || n >= cap) {
            fprintf(stderr, "mtp-oracle: invalid --drafts list: %s\n", s);
            exit(2);
        }
        out[n++] = (int)v;
        p = end;
        while (*p == ' ' || *p == '\t') p++;
        if (*p == ',') p++;
        else if (*p) {
            fprintf(stderr, "mtp-oracle: invalid --drafts list: %s\n", s);
            exit(2);
        }
    }
    return n;
}

static int snapshot_save(ds4_session *s, snapshot_t *snap, char *err, size_t errlen) {
    if (snap->fp) {
        fclose(snap->fp);
        snap->fp = NULL;
    }
    snap->fp = tmpfile();
    if (!snap->fp) {
        snprintf(err, errlen, "tmpfile failed: %s", strerror(errno));
        return 1;
    }
    snap->len = ds4_session_payload_bytes(s);
    if (ds4_session_save_payload(s, snap->fp, err, errlen) != 0) return 1;
    if (fflush(snap->fp) != 0) {
        snprintf(err, errlen, "snapshot flush failed: %s", strerror(errno));
        return 1;
    }
    rewind(snap->fp);
    return 0;
}

static int snapshot_load(ds4_session *s, snapshot_t *snap, char *err, size_t errlen) {
    if (!snap->fp) {
        snprintf(err, errlen, "no snapshot");
        return 1;
    }
    rewind(snap->fp);
    return ds4_session_load_payload(s, snap->fp, snap->len, err, errlen);
}

static void snapshot_free(snapshot_t *snap) {
    if (snap->fp) fclose(snap->fp);
    snap->fp = NULL;
    snap->len = 0;
}

static int argmax_excluding(ds4_session *s, int excluded) {
    ds4_token_score top[16];
    int n = ds4_session_top_logprobs(s, top, (int)(sizeof(top) / sizeof(top[0])));
    if (n > 0) {
        for (int i = 0; i < n; i++) {
            if (top[i].id != excluded) return top[i].id;
        }
    }
    int token = ds4_session_argmax(s);
    return token == excluded ? -1 : token;
}

static void tokens_copy_public(ds4_tokens *dst, const ds4_tokens *src) {
    dst->v = NULL;
    dst->len = 0;
    dst->cap = 0;
    for (int i = 0; i < src->len; i++) ds4_tokens_push(dst, src->v[i]);
}

int main(int argc, char **argv) {
    cfg_t cfg = parse_args(argc, argv);
    int drafts[32];
    int ndrafts = parse_drafts(cfg.draft_list, drafts, (int)(sizeof(drafts) / sizeof(drafts[0])));
    if (ndrafts <= 0) {
        fprintf(stderr, "mtp-oracle: no draft depths requested\n");
        return 2;
    }

    ds4_engine_options opt = {
        .model_path = cfg.model_path,
        .backend = cfg.backend,
        .n_threads = cfg.threads,
        .warm_weights = cfg.warm_weights,
        .quality = cfg.quality,
    };
    ds4_engine *engine = NULL;
    if (ds4_engine_open(&engine, &opt) != 0) return 1;

    char *text = read_file(cfg.prompt_path ? cfg.prompt_path : cfg.chat_prompt_path);
    ds4_tokens prompt = {0};
    if (cfg.chat_prompt_path) {
        ds4_encode_chat_prompt(engine, cfg.system, text, DS4_THINK_NONE, &prompt);
    } else {
        ds4_tokenize_text(engine, text, &prompt);
    }
    free(text);
    if (cfg.prompt_tokens > 0 && cfg.prompt_tokens < prompt.len) prompt.len = cfg.prompt_tokens;
    if (prompt.len <= 0) {
        fprintf(stderr, "mtp-oracle: empty prompt\n");
        ds4_tokens_free(&prompt);
        ds4_engine_close(engine);
        return 1;
    }
    if (cfg.ctx == 0) cfg.ctx = prompt.len + cfg.gen_tokens + 16;
    if (cfg.ctx <= prompt.len + cfg.gen_tokens) {
        fprintf(stderr, "mtp-oracle: --ctx must exceed prompt_tokens + gen_tokens\n");
        ds4_tokens_free(&prompt);
        ds4_engine_close(engine);
        return 2;
    }

    ds4_context_memory mem = ds4_context_memory_estimate(cfg.backend, cfg.ctx);
    fprintf(stderr,
            "mtp-oracle: prompt_tokens=%d gen_tokens=%d ctx=%d backend=%s prefill_cap=%u raw_cap=%u\n",
            prompt.len,
            cfg.gen_tokens,
            cfg.ctx,
            ds4_backend_name(cfg.backend),
            mem.prefill_cap,
            mem.raw_cap);

    ds4_session *session = NULL;
    if (ds4_session_create(&session, engine, cfg.ctx) != 0) {
        fprintf(stderr, "mtp-oracle: failed to create session\n");
        ds4_tokens_free(&prompt);
        ds4_engine_close(engine);
        return 1;
    }

    char err[256];
    const double prefill_t0 = now_sec();
    if (ds4_session_sync(session, &prompt, err, sizeof(err)) != 0) {
        fprintf(stderr, "mtp-oracle: prompt sync failed: %s\n", err);
        ds4_session_free(session);
        ds4_tokens_free(&prompt);
        ds4_engine_close(engine);
        return 1;
    }
    const double prefill_t1 = now_sec();

    snapshot_t prompt_snap = {0};
    if (snapshot_save(session, &prompt_snap, err, sizeof(err)) != 0) {
        fprintf(stderr, "mtp-oracle: prompt snapshot failed: %s\n", err);
        ds4_session_free(session);
        ds4_tokens_free(&prompt);
        ds4_engine_close(engine);
        return 1;
    }

    int *target = calloc((size_t)cfg.gen_tokens, sizeof(target[0]));
    int *ref_top = calloc((size_t)cfg.gen_tokens, sizeof(ref_top[0]));
    float *ref_next_lp = calloc((size_t)cfg.gen_tokens, sizeof(ref_next_lp[0]));
    if (!target || !ref_top || !ref_next_lp) {
        fprintf(stderr, "mtp-oracle: out of memory\n");
        return 1;
    }
    for (int i = 0; i < cfg.gen_tokens; i++) ref_next_lp[i] = NAN;

    const int eos = ds4_token_eos(engine);
    for (int i = 0; i < cfg.gen_tokens; i++) {
        int tok = argmax_excluding(session, eos);
        if (tok < 0) {
            fprintf(stderr, "mtp-oracle: failed to choose non-EOS token while generating target\n");
            return 1;
        }
        target[i] = tok;
        if (ds4_session_eval(session, tok, err, sizeof(err)) != 0) {
            fprintf(stderr, "mtp-oracle: target generation failed at %d: %s\n", i, err);
            return 1;
        }
    }

    if (snapshot_load(session, &prompt_snap, err, sizeof(err)) != 0) {
        fprintf(stderr, "mtp-oracle: restore before exact pass failed: %s\n", err);
        return 1;
    }

    const double exact_t0 = now_sec();
    for (int i = 0; i < cfg.gen_tokens; i++) {
        if (ds4_session_eval(session, target[i], err, sizeof(err)) != 0) {
            fprintf(stderr, "mtp-oracle: exact pass failed at %d: %s\n", i, err);
            return 1;
        }
        ref_top[i] = ds4_session_argmax(session);
        if (i + 1 < cfg.gen_tokens) {
            ds4_token_score sc;
            if (ds4_session_token_logprob(session, target[i + 1], &sc)) ref_next_lp[i] = sc.logprob;
        }
    }
    const double exact_t1 = now_sec();
    const double exact_ms = (exact_t1 - exact_t0) * 1000.0;
    const double exact_tps = exact_ms > 0.0 ? (double)cfg.gen_tokens / (exact_ms / 1000.0) : 0.0;

    printf("mode,draft_tokens,cycle_tokens,tokens,time_ms,tok_s,speedup_vs_exact,boundary_checks,top_mismatch,mean_next_logprob_delta,worst_next_logprob_delta\n");
    printf("exact,0,1,%d,%.3f,%.3f,1.000,0,0,0,0\n",
           cfg.gen_tokens,
           exact_ms,
           exact_tps);
    fflush(stdout);

    /* Force resumed prefill even for tiny oracle suffixes.  This is the batch
     * verifier/commit upper-bound we care about; exact baseline uses eval(). */
    setenv("DS4_METAL_RESUME_PREFILL_MIN", "1", 1);

    for (int id = 0; id < ndrafts; id++) {
        const int draft_n = drafts[id];
        if (draft_n <= 0) continue;
        if (snapshot_load(session, &prompt_snap, err, sizeof(err)) != 0) {
            fprintf(stderr, "mtp-oracle: restore before draft=%d failed: %s\n", draft_n, err);
            return 1;
        }
        ds4_tokens cur = {0};
        tokens_copy_public(&cur, &prompt);

        int pos = 0;
        int checks = 0;
        int mismatches = 0;
        double sum_delta = 0.0;
        int n_delta = 0;
        double worst_delta = DBL_MAX;
        double timed_s = 0.0;
        while (pos < cfg.gen_tokens) {
            const double eval_t0 = now_sec();
            if (ds4_session_eval(session, target[pos], err, sizeof(err)) != 0) {
                fprintf(stderr, "mtp-oracle: exact first token failed draft=%d pos=%d: %s\n", draft_n, pos, err);
                ds4_tokens_free(&cur);
                return 1;
            }
            const double eval_t1 = now_sec();
            timed_s += eval_t1 - eval_t0;
            ds4_tokens_push(&cur, target[pos]);
            pos++;

            int suffix = draft_n;
            if (suffix > cfg.gen_tokens - pos) suffix = cfg.gen_tokens - pos;
            if (suffix > 0) {
                for (int j = 0; j < suffix; j++) ds4_tokens_push(&cur, target[pos + j]);
                const double sync_t0 = now_sec();
                if (ds4_session_sync(session, &cur, err, sizeof(err)) != 0) {
                    fprintf(stderr, "mtp-oracle: oracle suffix sync failed draft=%d pos=%d suffix=%d: %s\n",
                            draft_n, pos, suffix, err);
                    ds4_tokens_free(&cur);
                    return 1;
                }
                const double sync_t1 = now_sec();
                timed_s += sync_t1 - sync_t0;
                pos += suffix;
            }

            const int ref_idx = pos - 1;
            if (ref_idx >= 0 && ref_idx < cfg.gen_tokens) {
                checks++;
                int top = ds4_session_argmax(session);
                if (top != ref_top[ref_idx]) mismatches++;
                if (pos < cfg.gen_tokens && isfinite(ref_next_lp[ref_idx])) {
                    ds4_token_score sc;
                    if (ds4_session_token_logprob(session, target[pos], &sc)) {
                        double delta = (double)sc.logprob - (double)ref_next_lp[ref_idx];
                        sum_delta += delta;
                        n_delta++;
                        if (delta < worst_delta) worst_delta = delta;
                    }
                }
            }
        }
        const double ms = timed_s * 1000.0;
        const double tps = timed_s > 0.0 ? (double)cfg.gen_tokens / timed_s : 0.0;
        const double speedup = exact_tps > 0.0 ? tps / exact_tps : 0.0;
        const double mean_delta = n_delta ? sum_delta / (double)n_delta : 0.0;
        if (worst_delta == DBL_MAX) worst_delta = 0.0;
        printf("oracle_spec,%d,%d,%d,%.3f,%.3f,%.3f,%d,%d,%.6g,%.6g\n",
               draft_n,
               draft_n + 1,
               cfg.gen_tokens,
               ms,
               tps,
               speedup,
               checks,
               mismatches,
               mean_delta,
               worst_delta);
        fflush(stdout);
        ds4_tokens_free(&cur);
    }

    fprintf(stderr,
            "mtp-oracle: initial prefill %.3f ms, target tokens generated once for oracle drafts\n",
            (prefill_t1 - prefill_t0) * 1000.0);

    free(ref_next_lp);
    free(ref_top);
    free(target);
    snapshot_free(&prompt_snap);
    ds4_session_free(session);
    ds4_tokens_free(&prompt);
    ds4_engine_close(engine);
    return 0;
}
